name: todomobx
description: Flutter todo app with mobx state management
version: 2.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
